import slamingo_cup.queries.matchups as Matchups
import slamingo_cup.queries.played_players as PlayedPlayers
import slamingo_cup.queries.player_awards as PlayerAwards
import slamingo_cup.queries.positional_points as PositionalPoints
import slamingo_cup.queries.power_rankings as PowerRankings
import slamingo_cup.queries.rolling_points as RollingPoints
import slamingo_cup.queries.standings as Standings
import slamingo_cup.queries.team_awards as TeamAwards
import slamingo_cup.queries.weekly_results as WeeklyResults
